//! Pure domain types for Arctis Sound Manager. No I/O.
pub mod capability;
pub mod device;
pub mod eq_bounds;
pub mod status;

pub use capability::Capability;
pub use device::DeviceId;
pub use eq_bounds::{
    db_to_volume_pct, db_to_volume_pct_cubic, CHANNEL_VOLUME_MAX_DB, CHANNEL_VOLUME_MIN_DB, EQ_FREQ_MAX_HZ,
    EQ_FREQ_MIN_HZ, EQ_GAIN_MAX_DB, EQ_GAIN_MIN_DB, EQ_Q_MAX, EQ_Q_MIN,
    MIC_ATTEN_LIMIT_MAX_DB, MIC_ATTEN_LIMIT_MIN_DB, MIC_COMP_MAKEUP_MAX_DB,
    MIC_COMP_MAKEUP_MIN_DB, MIC_COMP_RATIO_MAX, MIC_COMP_RATIO_MIN,
    MIC_COMP_THRESHOLD_MAX_DB, MIC_COMP_THRESHOLD_MIN_DB, MIC_GAIN_MAX_DB, MIC_GAIN_MIN_DB,
    MIC_GATE_THRESHOLD_MAX, MIC_GATE_THRESHOLD_MIN, MIC_HIGHPASS_MAX_HZ, MIC_HIGHPASS_MIN_HZ,
    MIC_VAD_GRACE_MAX_MS, MIC_VAD_GRACE_MIN_MS, MIC_VAD_RETRO_GRACE_MAX_MS,
    MIC_VAD_RETRO_GRACE_MIN_MS, MIC_VAD_THRESHOLD_MAX, MIC_VAD_THRESHOLD_MIN, VOLUME_PCT_MAX,
    VOLUME_PCT_MIN,
};
pub use status::{DeviceState, StatusValue};
